segment_write_key:
  default: ""
  description: "The Write Key for your Segment Source. Note: you must also copy the following URL to the 'content security policy script src' Site Setting. Replace the text &lt;write-key&gt; with your write key: https://cdn.segment.com/analytics.js/v1/&lt;write-key&gt;/analytics.min.js"
track_users:
  default: true
  description: "Call the Segment identify function when a user logs in or refreshes the site."
track_by_external_id:
  default: false
  description: "For sites with SSO enabled, track users by their external_id instead of by their Discourse id."
track_page:
  default: true
  description: "Track page visits by type (currently tracks 'Homepage', 'Topic', 'Category', and 'Tag' pages.)"
track_post_creation:
  default: false
  description: "Track topic and post creation. Returns topic_id, topic_slug for topics; topic_id, topic_slug, and post_number for posts."
